#' Estimate time-varying reproduction number using Wallinga-Lipsitch method with bootstrap confidence intervals
#'
#' This function implements the Wallinga-Lipsitch method (2007) for estimating the time-varying
#' case reproduction number (R_c) from incidence data. The case reproduction number represents
#' the average number of secondary infections generated by cases with symptom onset at time t.
#'
#' The method works by:
#' 1. Creating a pairwise comparison between all possible infector-infectee pairs
#' 2. Calculating the relative likelihood that case j infected case i based on their time difference
#'    and the serial interval distribution
#' 3. Aggregating these likelihoods to estimate the number of secondary cases generated by each case
#' 4. Applying right-truncation correction to account for yet-unobserved secondary cases
#' 5. Optionally calculating bootstrap confidence intervals by resampling individual cases
#' 6. Optionally shifting the estimates forward by one serial interval (if shift=TRUE)
#'    to align with instantaneous reproduction number estimates
#'
#' The function supports both gamma and normal distributions for the serial interval,
#' smoothing of estimates, and bootstrap-based confidence intervals.
#'
#' @param incidence Numeric vector of daily case counts
#' @param dates Vector of dates corresponding to the incidence data
#' @param si_mean Mean of the serial interval distribution
#' @param si_sd Standard deviation of the serial interval distribution
#' @param si_dist Distribution to use for serial interval ("gamma" or "normal")
#' @param smoothing Window size for smoothing estimates (0 for no smoothing)
#' @param bootstrap Logical; whether to compute bootstrap confidence intervals
#' @param n_bootstrap Number of bootstrap samples to generate
#' @param conf_level Confidence level for intervals (0.95 = 95% CI)
#' @param shift Logical; whether to shift estimates by one mean serial interval (TRUE) or not (FALSE).
#'        When TRUE, adds a 'shifted_date' column to align case reproduction number estimates with
#'        instantaneous reproduction number estimates for proper comparison.
#' @return Data frame with columns:
#'   - date: Original dates from input
#'   - incidence: Daily case counts
#'   - R: Estimated case reproduction number
#'   - R_corrected: Case reproduction number with right-truncation correction
#'   - If bootstrap=TRUE:
#'     - R_lower, R_upper: Confidence intervals for R
#'     - R_corrected_lower, R_corrected_upper: Confidence intervals for R_corrected
#'   - If shift=TRUE:
#'     - shifted_date: Dates shifted forward by one mean serial interval
#' @export
#' @references
#' Wallinga J & Lipsitch M (2007). How generation intervals shape the relationship between
#' growth rates and reproductive numbers. Proceedings of the Royal Society B: Biological Sciences,
#' 274(1609), 599-604.
#'
wallinga_lipsitch <- function(
  incidence,
  dates,
  si_mean,
  si_sd,
  si_dist = "gamma",
  smoothing = 0,
  bootstrap = FALSE,
  n_bootstrap = 1000,
  conf_level = 0.95,
  shift = FALSE
) {
  # Input validation
  stopifnot(length(incidence) == length(dates))
  stopifnot(is.numeric(incidence))
  stopifnot(all(incidence >= 0))
  stopifnot(si_mean > 0)
  stopifnot(si_sd > 0)
  stopifnot(si_dist %in% c("gamma", "normal"))

  # Create matrix of day differences and calculate serial interval probabilities
  day_diffs <- create_day_diff_matrix(dates)
  si_prob <- calculate_si_probability_matrix(
    day_diffs,
    si_mean,
    si_sd,
    si_dist
  )

  # Calculate point estimates
  point_estimates <- calculate_r_estimates(
    incidence,
    si_prob,
    dates,
    si_mean,
    si_sd,
    si_dist,
    smoothing
  )

  # Initialize result data frame
  result <- data.frame(
    date = dates,
    incidence = incidence,
    R = point_estimates$r,
    R_corrected = point_estimates$r_corrected
  )

  # Add bootstrap confidence intervals if requested
  if (bootstrap) {
    ci_estimates <- calculate_bootstrap_ci(
      incidence,
      si_prob,
      dates,
      si_mean,
      si_sd,
      si_dist,
      smoothing,
      n_bootstrap,
      conf_level
    )

    # Add to result data frame
    result$R_lower <- ci_estimates$r_lower
    result$R_upper <- ci_estimates$r_upper
    result$R_corrected_lower <- ci_estimates$r_corrected_lower
    result$R_corrected_upper <- ci_estimates$r_corrected_upper
  }

  # Apply shift if requested
  if (shift) {
    # Calculate the number of days to shift based on the mean serial interval
    shift_days <- round(si_mean)

    # Create new date vector that's shifted forward by the serial interval
    shifted_dates <- dates + shift_days

    # Add the shifted dates to the results dataframe
    result$shifted_date <- shifted_dates

    # Warn if shift extends beyond available data
    if (max(shifted_dates) > max(dates) + shift_days) {
      warning(
        "Shifted dates extend beyond the available data range. Interpret with caution."
      )
    }
  }

  return(result)
}
