name: R-CMD-check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: ['release']
        include:
          - os: ubuntu-latest
            r: 'devel'
    runs-on: ${{ matrix.os }}
    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          http-user-agent: ${{ matrix.r == 'devel' && 'release' || '' }}

      # Step 3: Set up Pandoc with a specific version
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'

      # Step 4: Fix pandoc-citeproc issue on Ubuntu
      - name: Fix pandoc-citeproc dependency
        if: runner.os == 'Linux'
        run: |
          mkdir -p .github
          echo 'modify:
            sysreqs:
              - from: pandoc-citeproc
                to: ""
              - from: bayesplot
                to: ""
              - from: loo
                to: ""' > .github/pkg.lock.modify

      # Step 5: Install system dependencies for Ubuntu
      - name: Install system dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y git libcurl4-openssl-dev libssl-dev make libcairo2-dev libfontconfig1-dev libfreetype6-dev zlib1g-dev libjpeg-dev libpng-dev libtiff-dev libicu-dev libfribidi-dev libharfbuzz-dev libxml2-dev

      # Step 6: Install R dependencies
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::RcppEigen
            any::rcmdcheck
            local::.
          needs: check

      # Step 7: Run R CMD check
      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          build-vignettes: true
          upload-logs: true

      # Step 8: Upload check results
      - name: Upload R CMD check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.r }}-results
          path: check-results/*.txt
