name: R-CMD-check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'release', pandoc_fix: true}
          - {os: ubuntu-latest, r: 'devel', pandoc_fix: true, http-user-agent: 'release'}
    runs-on: ${{ matrix.config.os }}
    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Step 1: Check out the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up R
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      # Step 3: Set up Pandoc with a specific version
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.1'

      # Step 4: Create package dependency modification file
      - name: Create sysreqs modification file
        if: runner.os == 'Linux'
        run: |
          mkdir -p .github
          cat > .github/pkg.lock.modify << 'EOF'
          modify:
            sysreqs:
              - from: pandoc-citeproc
                to: ""
              - from: bayesplot
                to: ""
              - from: loo
                to: ""
          EOF

      # Step 4: Install packages directly for Ubuntu with R-release
      - name: Install packages directly for Ubuntu with R-release
        if: matrix.config.pandoc_fix
        run: |
          sudo apt-get update
          sudo apt-get install -y git libcurl4-openssl-dev libssl-dev make libcairo2-dev \
            libfontconfig1-dev libfreetype6-dev zlib1g-dev libjpeg-dev libpng-dev \
            libtiff-dev libicu-dev libfribidi-dev libharfbuzz-dev libxml2-dev \
            texlive-latex-base texlive-fonts-recommended texlive-fonts-extra \
            texlive-latex-extra qpdf tidy

          # Install R package dependencies manually
          Rscript -e 'install.packages(c("remotes", "rcmdcheck", "covr", "RcppEigen"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

          # Install the package
          R CMD INSTALL .

      # Step 5: Install R dependencies for other platforms
      - name: Install R dependencies
        if: ${{ !matrix.config.pandoc_fix }}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::RcppEigen
            any::rcmdcheck
            local::.
          needs: check

      # Step 6: Run R CMD check
      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          build-vignettes: true
          upload-logs: true

      # Step 7: Upload check results
      - name: Upload R CMD check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-results
          path: check-results/*.txt
